sudo: false
language: erlang
otp_release:
  - 20.2
  - 19.3
  - 18.3
  - 17.5
  - R16B03-1
  - R15B03
before_script:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod u+x rebar3
script: "./rebar3 update && ./rebar3 compile"
