dist: trusty
sudo: false
language: erlang
otp_release:
  - 22.0.2
  - 21.3
  - 20.3
  - 19.3
  - 18.3

before_script:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod u+x rebar3
script: "./rebar3 update && ./rebar3 compile"
